# Generated by Django 3.0.6 on 2020-06-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_details',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='doctor_details',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='doctor_details',
            name='speciality',
        ),
    ]
