# Generated by Django 3.0.6 on 2020-06-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_', '0002_auto_20200606_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_details',
            old_name='address',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='doctor_details',
            old_name='name',
            new_name='username',
        ),
    ]
